export const businessCategories = [
  "Wedding Planners",
  "Day-of Coordinators",
  "Venues",
  "Photographers",
  "Videographers",
  "Florists",
  "Caterers",
  "Cake Designers",
  "DJs",
  "Live Bands",
  "Ceremony Musicians",
  "Officiants",
  "Transportation Services",
  "Bridal Shops",
  "Hair/Makeup Artists",
  "Jewelry Stores",
  "Decor Rental Companies",
  "Lighting Specialists",
  "Photo Booth Providers",
  "Hotels for Guests",
  "Rehearsal Dinner Venues",
  "Bartending Services",
  "Rental Companies",
  "Tailors & Alterations",
  "Mobile Bars",
];
